---
title: "usethis history"
format: markdown
editor: visual
knitr: 
  opts_chunk: 
    eval: false
---

## Purpose

As much as possible, we should use `{useths}` and other related packages to manage package infrastructure.

## Install packages

```{r}
renv::restore()
```

## Setup

```{r}
usethis::git_vaccinate()
```

## Description File

```{r}
desc::desc_coerce_authors_at_r()
usethis::use_roxygen_md()
```

### Descripton & Title

```{r}
desc::desc_set(
  "Title",
  "Wormy Paths"
)
```

```{r}
desc::desc_set(
  "Description",
  "This will make wormy paths."
)
```

### License

```{r}
# usethis::use_gpl3_license()
# usethis::use_mit_license()
```

### Authors

```{r}
usethis::use_author(
  given = "Josef",
  family = "Fruehwald",
  email = "jofrhwld@gmail.com",
  role = c("aut","cre")
)
```

```{r}
# usethis::use_author(
#   given = "foo",
#   family = "bar",
#   email = "foobar@gmail.com",
#   role = c("aut","cre")
# )
```

### Misc

```{r}
roxygen2::roxygenize(here::here())
```

## GitHub

```{r}
# run once
# usethis::use_readme_rmd()
```

```{r}
# run once
#usethis::use_github()
```

```{r}
# run once
usethis::use_github_action(name = "check-standard")
```

Eventually:

```{r}
# run once, eventually
# usethis::use_pkgdown()
# usethis::use_pkgdown_github_pages()
# usethis::use_logo("logo.svg")
```

## Packages

### Depends

If we use the native pipe, `|>`

```{r}
usethis::use_package("R", type = "Depends", min_version = "4.1")
```

### Imports

Anything we use in the code

```{r}
# probably
usethis::use_package("ggplot2")
usethis::use_package("marginaleffects")
usethis::use_package("collapse")
```

### Suggests

Anything we use just in vignettes, examples.

```{r}
#usethis::use_package("pkg", type = "Suggests")
```
